### PR TITLE
Budget app Final Review

### PR DESCRIPTION
**Pull request by fezzopro**
## PR Details

This pull request contains:

- Splash screen
  - A simple page with the name of your app (yes, you need to choose one), and links to the sign up and log in pages.
- Sign up and log in pages
  - The user should be able to register in the app with full name, email and password (all mandatory).
  - The user can log into the app using email and password.
  - If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).
- Home page (categories page)
  - When the user logs in, they are presented with the categories page.
  - For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
  - When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
  - There is a button "add a new category" at the bottom that brings the user to the page to create a new category.
- Transactions page
  - For a given category, the list of transactions is presented, ordered by the most recent.
  - At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
  - There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
  - When the user clicks on the "Back" button (<), the user navigates to the home page.
- "Add a new category" page
  - The user fills out a form to create a new category, indicating their name and icon (both mandatory).
  - The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
  - When the user clicks on the "Back" button (<), the user navigates to the home page.
- "Add a new transaction" page
  - The user fills out a form to create a new transaction with:
     - name (mandatory)
    - amount (mandatory)
    - categories (mandatory at least one)
  - The user click (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.
  - When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.

image

### CODE REVIEW

**Comment by fezzopro** [comment]
This PR correct the error on Gitflow mentioned in the previous PR https://github.com/fezzopro/Budget-app/pull/13

**Review by Olamarx — CHANGES_REQUESTED** [review]
Hi @fezzopro,

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Readme file professional ✔️
- Linters passed ✔️
- Project deployed and works as expected ✔️

## Required Changes ♻️
_Check the comments under the review._
- [ ] While you did a good job making the video and also sharing some pieces of code, it is required that you highlight an aspect of the codebase you wrote that is most interesting to you, so you showed some, but which one is most interesting to you?

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by fezzopro** [comment]
Thank you for your review @Olamarx 
I have recorded a new video illustrating the piece of code that I'm proud of in the new video

**Review by Munsa1 — CHANGES_REQUESTED** [review]
Hi @fezzopro , 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes
_Check the comments under the review._
:warning: Important :warning: 
- [ ] As requested it is required that you highlight an aspect of the codebase you wrote that is most interesting to you, you have NOT explicitly mentioned this in your video presentation which one is most interesting to you. Kindly do so.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by fezzopro** [comment]
Hi, @Munsa1 I have added a new link to the video that highlights the most interesting part of my codebase. I'm not sure what you meant by not adding that in the video. Can you please use the link below.
https://www.loom.com/share/36665fe544ba401faed3d1de801618b5?sid=e12da96e-5700-4ec0-910d-51562ba89b17

**Review by Whoistolu — APPROVED** [review]
### Hi @fezzopro 

Great job highlighting the parts of your code that you are proud of 👍🏽 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
